module.exports = "El proximo #IngressFS se realizara el 1 de febrero. Pueden participar desde 🇵🇪 en las siguientes sedes:"
+"\n\n **Arequipa**\n Museo Historico Guillermo Zegarra, 9 am\n ENL @MrPanquesito  RES @Cristhiannu"
+"\n\n **Camana**\n Plaza de Camana, 3 pm \n ENL M0NkeyDLuff1  RES MIGUELru739"
+"\n\n **Charcarilla**\n Plaza Central de Humaya - Huacho, 3 pm\n ENL @freddyshinan  RES Rafc15"
+"\n\n **Chimbote**\n Plaza Almirante Miguel Grau, 4 pm\n ENL @Rocerja  RES @RomA29mc"
+"\n\n **Huancayo**\n Plaza de la Constitucion, 2 pm \n ENL @LegacyAM  RES @KenshinCP"
+"\n\n **Huanuco**\n Puente Calicanto, 2 pm\n ENL @solnocturno  RES @miguelsz1"
+"\n\n **Huaral**\n Parque La Libertad, 3 pm\n ENL Tomax29  RES Ikaizer"
+"\n\n **Ica**\n Plazuela Francisco Bolognesi, 3 pm\n ENL @AnTiCrS  RES LadyBlack18"
+"\n\n **Lima**\n Parque Maria Reiche, 3 pm\n ENL @Diezzy  RES @JoseFoZZ"
+"\n\n **Pucallpa**\n Plaza de Armas de Pucallpa, 3 pm\n ENL @LinWolf  RES @nandofire"
+"\n\n **Puno**\n Ovalo Ramon Castilla, 2 pm\n ENL @RubenReaper  RES linocallata"
+"\n\n **Tarapoto**\n Plaza de Armas de Tarapoto, 3 pm\n ENL @michelosan93  RES @ajotamedic"
+"\n\n **Trujillo**\n Ovalo Larco, 3:30 pm\n ENL anaclaucc  RES @WolfCommand"
+"\n\n(Todas las tildes omitidas)"
+"\n\n#IFSPeru"
